import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import coding from "../public/coding.gif";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-pacifico logo-class">Mihir</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 font-bold"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="title">Mihir Bambhaniya</h2>
            <h3
              className="text-2xl py-2 dark:text-white md:text-3xl"
              style={{ fontWeight: "700" }}
            >
              Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              A curious mind on a journey to bring ideas into reality
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <div>
                <a href="https://github.com/axewhyzed" target="_blank">
                  <AiFillGithub />
                </a>
              </div>
              <div>
                <a
                  href="https://www.linkedin.com/in/mihir-bambhaniya/"
                  target="_blank"
                >
                  <AiFillLinkedin />
                </a>
              </div>
            </div>
            <div className="flex justify-center items-center">
              <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-100 md:w-100">
                <Image src={coding} layout="fill" objectFit="cover" />
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="border-teal-500 border-t-4 mx-auto w-16"></div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-500 text-center font-bold text-teal-500">
              About Me
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section>
          <div className="border-teal-500 border-t-4 mx-auto w-16"></div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-500 text-center font-bold text-teal-500">
              Projects
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              These are some of the projects I've created :
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <div className="relative">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                />

                <div className="absolute bottom-0 left-0 right-0 flex justify-center mb-4">
                  <button className="mr-2 px-4 py-2 bg-teal-600 text-white rounded-lg border-none hover:bg-teal-600 focus:outline-none transition-all duration-300 ease-in-out">
                    Demo
                  </button>

                  <button className="ml-2 px-4 py-2 bg-black text-white rounded-lg border-none hover:bg-gray-800 focus:outline-none transition-all duration-300 ease-in-out">
                    View Source
                  </button>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="relative">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                />

                <div className="absolute bottom-0 left-0 right-0 flex justify-center mb-4">
                  <button className="mr-2 px-4 py-2 bg-teal-600 text-white rounded-lg border-none hover:bg-teal-600 focus:outline-none transition-all duration-300 ease-in-out">
                    Demo
                  </button>

                  <button className="ml-2 px-4 py-2 bg-black text-white rounded-lg border-none hover:bg-gray-800 focus:outline-none transition-all duration-300 ease-in-out">
                    View Source
                  </button>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="relative">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web3}
                />

                <div className="absolute bottom-0 left-0 right-0 flex justify-center mb-4">
                  <button className="mr-2 px-4 py-2 bg-teal-600 text-white rounded-lg border-none hover:bg-teal-600 focus:outline-none transition-all duration-300 ease-in-out">
                    Demo
                  </button>

                  <button className="ml-2 px-4 py-2 bg-black text-white rounded-lg border-none hover:bg-gray-800 focus:outline-none transition-all duration-300 ease-in-out">
                    View Source
                  </button>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="relative">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web4}
                />

                <div className="absolute bottom-0 left-0 right-0 flex justify-center mb-4">
                  <button className="mr-2 px-4 py-2 bg-teal-600 text-white rounded-lg border-none hover:bg-teal-600 focus:outline-none transition-all duration-300 ease-in-out">
                    Demo
                  </button>

                  <button className="ml-2 px-4 py-2 bg-black text-white rounded-lg border-none hover:bg-gray-800 focus:outline-none transition-all duration-300 ease-in-out">
                    View Source
                  </button>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="relative">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web5}
                />

                <div className="absolute bottom-0 left-0 right-0 flex justify-center mb-4">
                  <button className="mr-2 px-4 py-2 bg-teal-600 text-white rounded-lg border-none hover:bg-teal-600 focus:outline-none transition-all duration-300 ease-in-out">
                    Demo
                  </button>

                  <button className="ml-2 px-4 py-2 bg-black text-white rounded-lg border-none hover:bg-gray-800 focus:outline-none transition-all duration-300 ease-in-out">
                    View Source
                  </button>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="relative">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web6}
                />

                <div className="absolute bottom-0 left-0 right-0 flex justify-center mb-4">
                  <button className="mr-2 px-4 py-2 bg-teal-600 text-white rounded-lg border-none hover:bg-teal-600 focus:outline-none transition-all duration-300 ease-in-out">
                    Demo
                  </button>

                  <button className="ml-2 px-4 py-2 bg-black text-white rounded-lg border-none hover:bg-gray-800 focus:outline-none transition-all duration-300 ease-in-out">
                    View Source
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="border-teal-500 border-t-4 mx-auto w-16"></div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-500 text-center font-bold text-teal-500">
              Contact Me
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center">
              Feel free to get in touch with me!
            </p>
            <form
              className="max-w-md mx-auto mt-6"
              action="https://api.web3forms.com/submit"
              method="POST"
            >
              <input
                type="hidden"
                name="access_key"
                value="0d2b7004-2751-4c55-9d2a-0082471c851b"
              />
              <div className="mb-4">
                <label htmlFor="name" className="block mb-1 text-teal-500">
                  Name
                </label>
                <input
                  type="text"
                  name="name"
                  id="name"
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-md text-gray-800 focus:outline-none focus:ring-teal-500 focus:border-teal-500"
                  required
                />
              </div>

              <div className="mb-4">
                <label htmlFor="email" className="block mb-1 text-teal-500">
                  Email
                </label>
                <input
                  type="email"
                  name="email"
                  id="email"
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-md text-gray-800 focus:outline-none focus:ring-teal-500 focus:border-teal-500"
                  required
                />
              </div>
              <div className="mb-4">
                <label htmlFor="message" className="block mb-1 text-teal-500">
                  Message
                </label>
                <textarea
                  id="message"
                  name="message"
                  rows="4"
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-md text-gray-800 resize-none focus:outline-none focus:ring-teal-500 focus:border-teal-500"
                  required
                ></textarea>
              </div>
              <button
                type="submit"
                className="bg-teal-500 hover:bg-teal-600 text-white px-4 py-2 rounded-md transition-colors duration-300 ease-in-out font-bold"
              >
                Submit
              </button>
            </form>
            <script
              src="https://web3forms.com/client/script.js"
              async
              defer
            ></script>
          </div>
        </section>
        <footer className="py-4">
          <div className="mx-auto max-w-screen-xl px-4">
            <p className="text-center text-lg">
              <span className="text-gradient-teal font-semibold">
                2023 - Mihir Bambhaniya
              </span>
            </p>
          </div>
        </footer>
      </main>
    </div>
  );
}
